export const CORS_PREFLIGHT_MAX_AGE_SECONDS = 86_400;
export const DEFAULT_THROTTLE_NAME = 'default';
export const DEFAULT_THROTTLE_TTL_MS = 60_000;
export const DEFAULT_THROTTLE_LIMIT = 120;
export const UNAUTHENTICATED_THROTTLE_NAME = 'unauthenticated';
export const UNAUTHENTICATED_THROTTLE_TTL_MS = 60_000;
export const UNAUTHENTICATED_THROTTLE_LIMIT = 30;
export const CREDENTIAL_THROTTLE_NAME = 'credential';
export const CREDENTIAL_THROTTLE_TTL_MS = 60_000;
export const CREDENTIAL_THROTTLE_LIMIT = 5;
export const SKIP_ALL_NAMED_THROTTLERS = {
  [DEFAULT_THROTTLE_NAME]: true,
  [UNAUTHENTICATED_THROTTLE_NAME]: true,
  [CREDENTIAL_THROTTLE_NAME]: true,
};
export const REQUEST_JSON_BODY_LIMIT = '100kb';
